service:
  name: aws-typescript-webapi

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 3

functions:
  Function:
    handler: handler.server
    events:
      # create image entry
      - http:
          method: post
          path: /images
      # get image entry
      - http:
          method: get
          path: /images/{id}
